// import './globals.css'
import './styles/styles.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//^ Importing Components
import Header from './components/Header'

export default function RootLayout({ children }) {
  	return (
		<>
			<header>
				<Header/>
			</header>

			<main>
				<body>{children}</body>
			</main>
		</>
  	)
}
